import "../styles/globals.css";
import "animate.css";
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <main>{children}</main>
        <Toaster richColors toastOptions={{ duration: 2000 }} />
      </body>
    </html>
  );
}
